# Overview

## Questions

- DK: Which schools are showing the best growth on math scores?
- Student: Which districts are showing greatest increase in their Hispanic/Latino population?

## Data

- DK: Math proficiency year over year
- Student: Enrollment by race year over year

# Data Wrangling

We'll get two years of data, tidy + clean it, and get it ready for analysis

## Importing Data

DK: I demonstrate how to do it, but then use already downloaded Excel spreadsheets
Student: Download and import my saved Excel spreadsheets

## Tidy Data

## Reshaping

pivot_longer()

## Missing Data

## Changing Variable Types

## Advanced Variable Creation

## Data Merging

DK: Merge school ids to school names
Student: Merge school ids to district ids + add district names

## Functions

## bind_rows() + bind_cols()

## Renaming Variables

## Exporting Data

# Data Visualization

- DK: Make a line chart that shows math growth over last 2 years
- Student: Make a line chart that shows growth of Latino population over last 5 years

Start with FT coronavirus graph that I tweeted about: https://twitter.com/dgkeyes/status/1237812892189093888

## Highlight

### Use Color



### Reorder

Show it with bar chart, even if we aren't doing it


## Declutter

### Remove axis titles

### Remove legends

### Remove backgrounds

## Explain

### Use Direct Labels

### Use Titles that Tell the Story

### Use Annotations

Show FT coronavirus charts here as examples
Switch to line chart and go back and do everything from above

### Scale labels

Make scale labels on y axis percents using percent_format()

## Make it Sparkle

### Custom Themes

### Custom Fonts

### ggplot extensions

## Misc

Functions again

# RMarkdown

## Advanced Markdown Text Formattting

## Tables

## Advanced YAML

## Inline R Code

## Making your reports shine: Word edition

## Making your reports shine: HTML edition

## Making your reports shine: PDF edition

## Presentations

## Dashboards

## Other Formats